# Generated by Django 4.1.5 on 2023-01-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('scoreAll', models.IntegerField()),
                ('card', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GestUser',
            fields=[
                ('guestUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=8, null=True)),
                ('winner', models.CharField(max_length=32, null=True)),
                ('ing', models.BooleanField()),
                ('standard', models.BooleanField()),
                ('score', models.IntegerField()),
                ('hostUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
                ('guestUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.gestuser')),
            ],
        ),
    ]
